[package]
name = "swaddle"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.7"
env_logger = "0.11.5"
log = "0.4.22"
